Docupdate
biopet/bastygeneratefasta pull request #2
Opened 2017-10-18 13:06 UTC by rhpvorderman

2017-10-19 08:35 UTC, DavyCats requested changes

2017-10-19 08:35 UTC, DavyCats commented on docs/MANUAL.md
> +java -jar Biopet-0.2.0.jar tool BastyGenerateFasta --inputVcf myVCF.vcf \
tool will not be needed anymore, simply call jar for tool directly

2017-10-19 08:35 UTC, DavyCats commented on docs/MANUAL.md
> +java -jar Biopet-0.2.0.jar tool BastyGenerateFasta --bamFile myBam.bam \
tool will not be needed anymore, simply call jar for tool directly

2017-10-19 08:35 UTC, DavyCats commented on docs/MANUAL.md
> +java -jar Biopet-0.2.0.jar tool BastyGenerateFasta --inputVcf myVCF.vcf --bamFile myBam.bam \
tool will not be needed anymore, simply call jar for tool directly

2017-10-19 09:13 UTC, rhpvorderman commented
Done

2017-10-19 14:04 UTC, DavyCats commented on docs/INSTALLATION.md
> +java -jar <tool>-version.jar --help
shouldn't the jar be changed here too?

2017-10-20 11:25 UTC, rhpvorderman commented on docs/INSTALLATION.md
> +java -jar <tool>-version.jar --help
done

2017-10-20 14:35 UTC, DavyCats approved these changes

2017-10-20 14:42 UTC, merged